spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  rabbitmq:
      host: localhost
      port: 5679
      username: ${RABBIT_USERNAME}
      password: ${RABBIT_PASSWORD}
server:
  port: 9093
