spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skt-task
    username: jxjxjxm
    password: JJJM214332
    generate-dll: true
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: create-drop
  rabbitmq:
        host: localhost
        port: 5679
        username: ${RABBIT_USERNAME}
        password: ${RABBIT_PASSWORD}
server:
  port: 8080


