spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skt-task
    username: jxjxjxm
    password: JJJM214332
    generate-dll: true
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: create-drop
  rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
  cloud:
    stream:
      bindings:
        input:
          destination: productOrders
          group: productOrdersIntakeGroup

server:
  port: 8080


