spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skt-task
    username: jxjxjxm
    password: JJJM214332
    generate-dll: true
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: create-drop
  rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
  cloud:
    stream:
      bindings:
        createProductsChannel:
          destination: productsExchange
          contentType: application/json
          group: productsQueue
        requestProductsChannel:
          destination: requestExchange
          contentType: application/json
          group: requestsQueue
        receiveProductsChannel:
          destination: receiveProductsExchange
          group: receiveProductsQueue

server:
  port: 8080


